apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-sysctl
rules:
- apiGroups:
  - extensions
  resourceNames:
  - custom-sysctl-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use