apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: custom-sysctl-psp
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
      - max: 65535
        min: 1
    rule: MustRunAs
  requiredDropCapabilities:
    - ALL
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
      - max: 65535
        min: 1
    rule: MustRunAs
  volumes:
    - configMap
    - emptyDir
    - projected
    - secret
    - downwardAPI
    - persistentVolumeClaim
  allowedUnsafeSysctls:
    - net.core.somaxconn
    - vm.max_map_count
    - net.ipv4.tcp_retries2
